name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      - uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build
      - run: ls -la dist  # Debug step to confirm build output
      - uses: peaceiris/actions-gh-pages@v4  # Updated to v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true  # Ensures a clean gh-pages branch
